# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2

updates:
  # Composer dependencies (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "Thavarshan"
    assignees:
      - "Thavarshan"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"
    ignore:
      # Ignore patch updates for stable packages
      - dependency-name: "guzzlehttp/guzzle"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "react/*"
        update-types: ["version-update:semver-patch"]
    groups:
      guzzle:
        patterns:
          - "guzzlehttp/*"
      react:
        patterns:
          - "react/*"
      testing:
        patterns:
          - "phpunit/*"
          - "mockery/*"
      dev-tools:
        patterns:
          - "phpstan/*"
          - "laravel/pint"
          - "friendsofphp/php-cs-fixer"
          - "tightenco/duster"

  # NPM dependencies (Documentation)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "Thavarshan"
    commit-message:
      prefix: "deps(npm)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Major version updates need manual review
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "Thavarshan"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions:
        patterns:
          - "actions/*"
        exclude-patterns:
          - "actions/checkout" # Keep checkout updates separate
